package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Area was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Area extends CayenneDataObject {

    public static final String AREA_CD_PROPERTY = "areaCd";
    public static final String EMP_NO_PROPERTY = "empNo";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SHORT_NAME_PROPERTY = "shortName";

    public static final String AREACD_PK_COLUMN = "AREACD";

    public void setAreaCd(int areaCd) {
        writeProperty(AREA_CD_PROPERTY, areaCd);
    }
    public int getAreaCd() {
        Object value = readProperty(AREA_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmpNo(int empNo) {
        writeProperty(EMP_NO_PROPERTY, empNo);
    }
    public int getEmpNo() {
        Object value = readProperty(EMP_NO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

}
