package jp.co.nexus.crm.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Area;
import jp.co.nexus.crm.db.NCCalldoc;
import jp.co.nexus.crm.db.NCCustomer;
import jp.co.nexus.crm.db.NCDivision;
import jp.co.nexus.crm.db.NCPerson;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String EMP_NO_PROPERTY = "empNo";
    public static final String EMP_NO_ED_PROPERTY = "empNoEd";
    public static final String ENTRYMD_PROPERTY = "entrymd";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String RETRYMD_PROPERTY = "retrymd";
    public static final String AREA_PROPERTY = "area";
    public static final String CALLDOCS_PROPERTY = "calldocs";
    public static final String CUSTOMERS_PROPERTY = "customers";
    public static final String DIVISIONS_PROPERTY = "divisions";
    public static final String PERSONS_PROPERTY = "persons";

    public static final String EMPNO_PK_COLUMN = "EMPNO";

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setEmpNo(int empNo) {
        writeProperty(EMP_NO_PROPERTY, empNo);
    }
    public int getEmpNo() {
        Object value = readProperty(EMP_NO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmpNoEd(int empNoEd) {
        writeProperty(EMP_NO_ED_PROPERTY, empNoEd);
    }
    public int getEmpNoEd() {
        Object value = readProperty(EMP_NO_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEntrymd(Integer entrymd) {
        writeProperty(ENTRYMD_PROPERTY, entrymd);
    }
    public Integer getEntrymd() {
        return (Integer)readProperty(ENTRYMD_PROPERTY);
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setPassword(int password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public int getPassword() {
        Object value = readProperty(PASSWORD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setRetrymd(Integer retrymd) {
        writeProperty(RETRYMD_PROPERTY, retrymd);
    }
    public Integer getRetrymd() {
        return (Integer)readProperty(RETRYMD_PROPERTY);
    }

    public void setArea(Area area) {
        setToOneTarget(AREA_PROPERTY, area, true);
    }

    public Area getArea() {
        return (Area)readProperty(AREA_PROPERTY);
    }


    public void addToCalldocs(NCCalldoc obj) {
        addToManyTarget(CALLDOCS_PROPERTY, obj, true);
    }
    public void removeFromCalldocs(NCCalldoc obj) {
        removeToManyTarget(CALLDOCS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NCCalldoc> getCalldocs() {
        return (List<NCCalldoc>)readProperty(CALLDOCS_PROPERTY);
    }


    public void addToCustomers(NCCustomer obj) {
        addToManyTarget(CUSTOMERS_PROPERTY, obj, true);
    }
    public void removeFromCustomers(NCCustomer obj) {
        removeToManyTarget(CUSTOMERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NCCustomer> getCustomers() {
        return (List<NCCustomer>)readProperty(CUSTOMERS_PROPERTY);
    }


    public void addToDivisions(NCDivision obj) {
        addToManyTarget(DIVISIONS_PROPERTY, obj, true);
    }
    public void removeFromDivisions(NCDivision obj) {
        removeToManyTarget(DIVISIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NCDivision> getDivisions() {
        return (List<NCDivision>)readProperty(DIVISIONS_PROPERTY);
    }


    public void addToPersons(NCPerson obj) {
        addToManyTarget(PERSONS_PROPERTY, obj, true);
    }
    public void removeFromPersons(NCPerson obj) {
        removeToManyTarget(PERSONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NCPerson> getPersons() {
        return (List<NCPerson>)readProperty(PERSONS_PROPERTY);
    }


}
