package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _NCCommonNm was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCCommonNm extends CayenneDataObject {

    public static final String COMMON_CD_PROPERTY = "commonCd";
    public static final String COMMON_KBN_PROPERTY = "commonKbn";
    public static final String EMP_NO_PROPERTY = "empNo";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String TOKKI_C1_PROPERTY = "tokkiC1";
    public static final String TOKKI_C2_PROPERTY = "tokkiC2";
    public static final String TOKKI_C3_PROPERTY = "tokkiC3";
    public static final String TOKKI_C4_PROPERTY = "tokkiC4";
    public static final String TOKKI_C5_PROPERTY = "tokkiC5";
    public static final String TOKKI_N1_PROPERTY = "tokkiN1";
    public static final String TOKKI_N2_PROPERTY = "tokkiN2";
    public static final String TOKKI_N3_PROPERTY = "tokkiN3";
    public static final String TOKKI_N4_PROPERTY = "tokkiN4";
    public static final String TOKKI_N5_PROPERTY = "tokkiN5";

    public static final String COMMONCD_PK_COLUMN = "COMMONCD";
    public static final String COMMONKBN_PK_COLUMN = "COMMONKBN";

    public void setCommonCd(int commonCd) {
        writeProperty(COMMON_CD_PROPERTY, commonCd);
    }
    public int getCommonCd() {
        Object value = readProperty(COMMON_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCommonKbn(int commonKbn) {
        writeProperty(COMMON_KBN_PROPERTY, commonKbn);
    }
    public int getCommonKbn() {
        Object value = readProperty(COMMON_KBN_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmpNo(int empNo) {
        writeProperty(EMP_NO_PROPERTY, empNo);
    }
    public int getEmpNo() {
        Object value = readProperty(EMP_NO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

    public void setTokkiC1(String tokkiC1) {
        writeProperty(TOKKI_C1_PROPERTY, tokkiC1);
    }
    public String getTokkiC1() {
        return (String)readProperty(TOKKI_C1_PROPERTY);
    }

    public void setTokkiC2(String tokkiC2) {
        writeProperty(TOKKI_C2_PROPERTY, tokkiC2);
    }
    public String getTokkiC2() {
        return (String)readProperty(TOKKI_C2_PROPERTY);
    }

    public void setTokkiC3(String tokkiC3) {
        writeProperty(TOKKI_C3_PROPERTY, tokkiC3);
    }
    public String getTokkiC3() {
        return (String)readProperty(TOKKI_C3_PROPERTY);
    }

    public void setTokkiC4(String tokkiC4) {
        writeProperty(TOKKI_C4_PROPERTY, tokkiC4);
    }
    public String getTokkiC4() {
        return (String)readProperty(TOKKI_C4_PROPERTY);
    }

    public void setTokkiC5(String tokkiC5) {
        writeProperty(TOKKI_C5_PROPERTY, tokkiC5);
    }
    public String getTokkiC5() {
        return (String)readProperty(TOKKI_C5_PROPERTY);
    }

    public void setTokkiN1(int tokkiN1) {
        writeProperty(TOKKI_N1_PROPERTY, tokkiN1);
    }
    public int getTokkiN1() {
        Object value = readProperty(TOKKI_N1_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkiN2(int tokkiN2) {
        writeProperty(TOKKI_N2_PROPERTY, tokkiN2);
    }
    public int getTokkiN2() {
        Object value = readProperty(TOKKI_N2_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkiN3(int tokkiN3) {
        writeProperty(TOKKI_N3_PROPERTY, tokkiN3);
    }
    public int getTokkiN3() {
        Object value = readProperty(TOKKI_N3_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkiN4(int tokkiN4) {
        writeProperty(TOKKI_N4_PROPERTY, tokkiN4);
    }
    public int getTokkiN4() {
        Object value = readProperty(TOKKI_N4_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkiN5(int tokkiN5) {
        writeProperty(TOKKI_N5_PROPERTY, tokkiN5);
    }
    public int getTokkiN5() {
        Object value = readProperty(TOKKI_N5_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

}
