package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Area;
import jp.co.nexus.crm.db.Employee;

/**
 * Class _NCCustomer was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCCustomer extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String ANKEN_INFO_PROPERTY = "ankenInfo";
    public static final String APPROVAL_RIGHTS_PROPERTY = "approvalRights";
    public static final String BACKBONE_PROPERTY = "backbone";
    public static final String CUST_RANK06_PROPERTY = "custRank06";
    public static final String CUST_RANK07_PROPERTY = "custRank07";
    public static final String CUST_RANK08_PROPERTY = "custRank08";
    public static final String CUST_RANK09_PROPERTY = "custRank09";
    public static final String CUST_RANK10_PROPERTY = "custRank10";
    public static final String CUSTOMER_CD_ED_PROPERTY = "customerCdEd";
    public static final String EMAIL1_PROPERTY = "email1";
    public static final String EMAIL2_PROPERTY = "email2";
    public static final String ITEM_RANK08_PROPERTY = "itemRank08";
    public static final String ITEM_RANK09_PROPERTY = "itemRank09";
    public static final String ITEM_RANK10_PROPERTY = "itemRank10";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String NUMBER_OF_PEOPLE_PROPERTY = "numberOfPeople";
    public static final String OUTSIDE_MAKE_KBN_PROPERTY = "outsideMakeKbn";
    public static final String OUTSIDE_MAKE_TOK_PROPERTY = "outsideMakeTok";
    public static final String PERSONNEL_PROPOSED_PROPERTY = "personnelProposed";
    public static final String POST_NO_PROPERTY = "postNo";
    public static final String RECEIVING_PROPERTY = "receiving";
    public static final String RELATIONSHIP_PROPERTY = "relationship";
    public static final String SALES_PROPERTY = "sales";
    public static final String SALES_CHANNELS_PROPERTY = "salesChannels";
    public static final String STAFF_PROPERTY = "staff";
    public static final String TEL_NO1_PROPERTY = "telNo1";
    public static final String TEL_NO2_PROPERTY = "telNo2";
    public static final String UNIT_PRICE_PROPERTY = "unitPrice";
    public static final String WORK_INFO_PROPERTY = "workInfo";
    public static final String AREA_PROPERTY = "area";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String CUSTOMERCD_PK_COLUMN = "CUSTOMERCD";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setAnkenInfo(int ankenInfo) {
        writeProperty(ANKEN_INFO_PROPERTY, ankenInfo);
    }
    public int getAnkenInfo() {
        Object value = readProperty(ANKEN_INFO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setApprovalRights(int approvalRights) {
        writeProperty(APPROVAL_RIGHTS_PROPERTY, approvalRights);
    }
    public int getApprovalRights() {
        Object value = readProperty(APPROVAL_RIGHTS_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setBackbone(int backbone) {
        writeProperty(BACKBONE_PROPERTY, backbone);
    }
    public int getBackbone() {
        Object value = readProperty(BACKBONE_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustRank06(int custRank06) {
        writeProperty(CUST_RANK06_PROPERTY, custRank06);
    }
    public int getCustRank06() {
        Object value = readProperty(CUST_RANK06_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustRank07(int custRank07) {
        writeProperty(CUST_RANK07_PROPERTY, custRank07);
    }
    public int getCustRank07() {
        Object value = readProperty(CUST_RANK07_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustRank08(int custRank08) {
        writeProperty(CUST_RANK08_PROPERTY, custRank08);
    }
    public int getCustRank08() {
        Object value = readProperty(CUST_RANK08_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustRank09(int custRank09) {
        writeProperty(CUST_RANK09_PROPERTY, custRank09);
    }
    public int getCustRank09() {
        Object value = readProperty(CUST_RANK09_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustRank10(int custRank10) {
        writeProperty(CUST_RANK10_PROPERTY, custRank10);
    }
    public int getCustRank10() {
        Object value = readProperty(CUST_RANK10_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustomerCdEd(int customerCdEd) {
        writeProperty(CUSTOMER_CD_ED_PROPERTY, customerCdEd);
    }
    public int getCustomerCdEd() {
        Object value = readProperty(CUSTOMER_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmail1(String email1) {
        writeProperty(EMAIL1_PROPERTY, email1);
    }
    public String getEmail1() {
        return (String)readProperty(EMAIL1_PROPERTY);
    }

    public void setEmail2(String email2) {
        writeProperty(EMAIL2_PROPERTY, email2);
    }
    public String getEmail2() {
        return (String)readProperty(EMAIL2_PROPERTY);
    }

    public void setItemRank08(int itemRank08) {
        writeProperty(ITEM_RANK08_PROPERTY, itemRank08);
    }
    public int getItemRank08() {
        Object value = readProperty(ITEM_RANK08_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setItemRank09(int itemRank09) {
        writeProperty(ITEM_RANK09_PROPERTY, itemRank09);
    }
    public int getItemRank09() {
        Object value = readProperty(ITEM_RANK09_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setItemRank10(int itemRank10) {
        writeProperty(ITEM_RANK10_PROPERTY, itemRank10);
    }
    public int getItemRank10() {
        Object value = readProperty(ITEM_RANK10_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNumberOfPeople(int numberOfPeople) {
        writeProperty(NUMBER_OF_PEOPLE_PROPERTY, numberOfPeople);
    }
    public int getNumberOfPeople() {
        Object value = readProperty(NUMBER_OF_PEOPLE_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOutsideMakeKbn(String outsideMakeKbn) {
        writeProperty(OUTSIDE_MAKE_KBN_PROPERTY, outsideMakeKbn);
    }
    public String getOutsideMakeKbn() {
        return (String)readProperty(OUTSIDE_MAKE_KBN_PROPERTY);
    }

    public void setOutsideMakeTok(String outsideMakeTok) {
        writeProperty(OUTSIDE_MAKE_TOK_PROPERTY, outsideMakeTok);
    }
    public String getOutsideMakeTok() {
        return (String)readProperty(OUTSIDE_MAKE_TOK_PROPERTY);
    }

    public void setPersonnelProposed(int personnelProposed) {
        writeProperty(PERSONNEL_PROPOSED_PROPERTY, personnelProposed);
    }
    public int getPersonnelProposed() {
        Object value = readProperty(PERSONNEL_PROPOSED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setPostNo(String postNo) {
        writeProperty(POST_NO_PROPERTY, postNo);
    }
    public String getPostNo() {
        return (String)readProperty(POST_NO_PROPERTY);
    }

    public void setReceiving(int receiving) {
        writeProperty(RECEIVING_PROPERTY, receiving);
    }
    public int getReceiving() {
        Object value = readProperty(RECEIVING_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setRelationship(int relationship) {
        writeProperty(RELATIONSHIP_PROPERTY, relationship);
    }
    public int getRelationship() {
        Object value = readProperty(RELATIONSHIP_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setSales(int sales) {
        writeProperty(SALES_PROPERTY, sales);
    }
    public int getSales() {
        Object value = readProperty(SALES_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setSalesChannels(int salesChannels) {
        writeProperty(SALES_CHANNELS_PROPERTY, salesChannels);
    }
    public int getSalesChannels() {
        Object value = readProperty(SALES_CHANNELS_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setStaff(int staff) {
        writeProperty(STAFF_PROPERTY, staff);
    }
    public int getStaff() {
        Object value = readProperty(STAFF_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTelNo1(String telNo1) {
        writeProperty(TEL_NO1_PROPERTY, telNo1);
    }
    public String getTelNo1() {
        return (String)readProperty(TEL_NO1_PROPERTY);
    }

    public void setTelNo2(String telNo2) {
        writeProperty(TEL_NO2_PROPERTY, telNo2);
    }
    public String getTelNo2() {
        return (String)readProperty(TEL_NO2_PROPERTY);
    }

    public void setUnitPrice(int unitPrice) {
        writeProperty(UNIT_PRICE_PROPERTY, unitPrice);
    }
    public int getUnitPrice() {
        Object value = readProperty(UNIT_PRICE_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setWorkInfo(int workInfo) {
        writeProperty(WORK_INFO_PROPERTY, workInfo);
    }
    public int getWorkInfo() {
        Object value = readProperty(WORK_INFO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setArea(Area area) {
        setToOneTarget(AREA_PROPERTY, area, true);
    }

    public Area getArea() {
        return (Area)readProperty(AREA_PROPERTY);
    }


    public void setEmployee(Employee employee) {
        setToOneTarget(EMPLOYEE_PROPERTY, employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty(EMPLOYEE_PROPERTY);
    }


}
