package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _NCDivision was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCDivision extends CayenneDataObject {

    public static final String AREA_CD_PROPERTY = "areaCd";
    public static final String CUSTOMER_CD_PROPERTY = "customerCd";
    public static final String CUSTOMER_CD_ED_PROPERTY = "customerCdEd";
    public static final String DIVISION_CD_PROPERTY = "divisionCd";
    public static final String DIVISION_CD_ED_PROPERTY = "divisionCdEd";
    public static final String EMP_NO_PROPERTY = "empNo";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String TOKKI_PROPERTY = "tokki";

    public static final String AREACD_PK_COLUMN = "AREACD";
    public static final String CUSTOMERCD_PK_COLUMN = "CUSTOMERCD";
    public static final String CUSTOMERCD_ED_PK_COLUMN = "CUSTOMERCD_ED";
    public static final String DIVISIONCD_PK_COLUMN = "DIVISIONCD";
    public static final String DIVISIONCD_ED_PK_COLUMN = "DIVISIONCD_ED";

    public void setAreaCd(int areaCd) {
        writeProperty(AREA_CD_PROPERTY, areaCd);
    }
    public int getAreaCd() {
        Object value = readProperty(AREA_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustomerCd(int customerCd) {
        writeProperty(CUSTOMER_CD_PROPERTY, customerCd);
    }
    public int getCustomerCd() {
        Object value = readProperty(CUSTOMER_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustomerCdEd(int customerCdEd) {
        writeProperty(CUSTOMER_CD_ED_PROPERTY, customerCdEd);
    }
    public int getCustomerCdEd() {
        Object value = readProperty(CUSTOMER_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setDivisionCd(int divisionCd) {
        writeProperty(DIVISION_CD_PROPERTY, divisionCd);
    }
    public int getDivisionCd() {
        Object value = readProperty(DIVISION_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setDivisionCdEd(int divisionCdEd) {
        writeProperty(DIVISION_CD_ED_PROPERTY, divisionCdEd);
    }
    public int getDivisionCdEd() {
        Object value = readProperty(DIVISION_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmpNo(int empNo) {
        writeProperty(EMP_NO_PROPERTY, empNo);
    }
    public int getEmpNo() {
        Object value = readProperty(EMP_NO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

    public void setTokki(String tokki) {
        writeProperty(TOKKI_PROPERTY, tokki);
    }
    public String getTokki() {
        return (String)readProperty(TOKKI_PROPERTY);
    }

}
