package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Area;
import jp.co.nexus.crm.db.Employee;

/**
 * Class _NCDivision was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCDivision extends CayenneDataObject {

    public static final String CUSTOMER_CD_ED_PROPERTY = "customerCdEd";
    public static final String CUSTOMERCD_PROPERTY = "customercd";
    public static final String DIVISION_CD_ED_PROPERTY = "divisionCdEd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String TOKKI_PROPERTY = "tokki";
    public static final String AREA_PROPERTY = "area";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String DIVISIONCD_PK_COLUMN = "DIVISIONCD";

    public void setCustomerCdEd(int customerCdEd) {
        writeProperty(CUSTOMER_CD_ED_PROPERTY, customerCdEd);
    }
    public int getCustomerCdEd() {
        Object value = readProperty(CUSTOMER_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustomercd(Integer customercd) {
        writeProperty(CUSTOMERCD_PROPERTY, customercd);
    }
    public Integer getCustomercd() {
        return (Integer)readProperty(CUSTOMERCD_PROPERTY);
    }

    public void setDivisionCdEd(int divisionCdEd) {
        writeProperty(DIVISION_CD_ED_PROPERTY, divisionCdEd);
    }
    public int getDivisionCdEd() {
        Object value = readProperty(DIVISION_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

    public void setTokki(String tokki) {
        writeProperty(TOKKI_PROPERTY, tokki);
    }
    public String getTokki() {
        return (String)readProperty(TOKKI_PROPERTY);
    }

    public void setArea(Area area) {
        setToOneTarget(AREA_PROPERTY, area, true);
    }

    public Area getArea() {
        return (Area)readProperty(AREA_PROPERTY);
    }


    public void setEmployee(Employee employee) {
        setToOneTarget(EMPLOYEE_PROPERTY, employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty(EMPLOYEE_PROPERTY);
    }


}
