package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Employee;

/**
 * Class _NCOutsideMake was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCOutsideMake extends CayenneDataObject {

    public static final String AREA_CD_PROPERTY = "areaCd";
    public static final String COMPETE_PROPERTY = "compete";
    public static final String CUSTOMER_CD_ED_PROPERTY = "customerCdEd";
    public static final String INTARVIEW_PROPERTY = "intarview";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MARKET_PRICE_PROPERTY = "marketPrice";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NEED_SKILL_PROPERTY = "needSkill";
    public static final String NUMBER_OF_PEOPLE_PROPERTY = "numberOfPeople";
    public static final String OSM_YMD_PROPERTY = "osmYmd";
    public static final String OSM_YMD_SEQ_PROPERTY = "osmYmdSeq";
    public static final String OUTSIDE_MAKE_DTL_PROPERTY = "outsideMakeDtl";
    public static final String OUTSIDE_MAKE_KBN_PROPERTY = "outsideMakeKbn";
    public static final String PERIOD_PROPERTY = "period";
    public static final String PERSON_NO_PROPERTY = "personNo";
    public static final String PERSON_NO_ED_PROPERTY = "personNoEd";
    public static final String PLACE_PROPERTY = "place";
    public static final String SALES_CHANNEL_PROPERTY = "salesChannel";
    public static final String STATE_PROPERTY = "state";
    public static final String WORK_PROPERTY = "work";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String CUSTOMERCD_PK_COLUMN = "CUSTOMERCD";

    public void setAreaCd(int areaCd) {
        writeProperty(AREA_CD_PROPERTY, areaCd);
    }
    public int getAreaCd() {
        Object value = readProperty(AREA_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCompete(String compete) {
        writeProperty(COMPETE_PROPERTY, compete);
    }
    public String getCompete() {
        return (String)readProperty(COMPETE_PROPERTY);
    }

    public void setCustomerCdEd(int customerCdEd) {
        writeProperty(CUSTOMER_CD_ED_PROPERTY, customerCdEd);
    }
    public int getCustomerCdEd() {
        Object value = readProperty(CUSTOMER_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setIntarview(int intarview) {
        writeProperty(INTARVIEW_PROPERTY, intarview);
    }
    public int getIntarview() {
        Object value = readProperty(INTARVIEW_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setMarketPrice(String marketPrice) {
        writeProperty(MARKET_PRICE_PROPERTY, marketPrice);
    }
    public String getMarketPrice() {
        return (String)readProperty(MARKET_PRICE_PROPERTY);
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setNeedSkill(String needSkill) {
        writeProperty(NEED_SKILL_PROPERTY, needSkill);
    }
    public String getNeedSkill() {
        return (String)readProperty(NEED_SKILL_PROPERTY);
    }

    public void setNumberOfPeople(int numberOfPeople) {
        writeProperty(NUMBER_OF_PEOPLE_PROPERTY, numberOfPeople);
    }
    public int getNumberOfPeople() {
        Object value = readProperty(NUMBER_OF_PEOPLE_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOsmYmd(int osmYmd) {
        writeProperty(OSM_YMD_PROPERTY, osmYmd);
    }
    public int getOsmYmd() {
        Object value = readProperty(OSM_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOsmYmdSeq(int osmYmdSeq) {
        writeProperty(OSM_YMD_SEQ_PROPERTY, osmYmdSeq);
    }
    public int getOsmYmdSeq() {
        Object value = readProperty(OSM_YMD_SEQ_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOutsideMakeDtl(int outsideMakeDtl) {
        writeProperty(OUTSIDE_MAKE_DTL_PROPERTY, outsideMakeDtl);
    }
    public int getOutsideMakeDtl() {
        Object value = readProperty(OUTSIDE_MAKE_DTL_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOutsideMakeKbn(String outsideMakeKbn) {
        writeProperty(OUTSIDE_MAKE_KBN_PROPERTY, outsideMakeKbn);
    }
    public String getOutsideMakeKbn() {
        return (String)readProperty(OUTSIDE_MAKE_KBN_PROPERTY);
    }

    public void setPeriod(String period) {
        writeProperty(PERIOD_PROPERTY, period);
    }
    public String getPeriod() {
        return (String)readProperty(PERIOD_PROPERTY);
    }

    public void setPersonNo(int personNo) {
        writeProperty(PERSON_NO_PROPERTY, personNo);
    }
    public int getPersonNo() {
        Object value = readProperty(PERSON_NO_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setPersonNoEd(int personNoEd) {
        writeProperty(PERSON_NO_ED_PROPERTY, personNoEd);
    }
    public int getPersonNoEd() {
        Object value = readProperty(PERSON_NO_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setPlace(String place) {
        writeProperty(PLACE_PROPERTY, place);
    }
    public String getPlace() {
        return (String)readProperty(PLACE_PROPERTY);
    }

    public void setSalesChannel(String salesChannel) {
        writeProperty(SALES_CHANNEL_PROPERTY, salesChannel);
    }
    public String getSalesChannel() {
        return (String)readProperty(SALES_CHANNEL_PROPERTY);
    }

    public void setState(String state) {
        writeProperty(STATE_PROPERTY, state);
    }
    public String getState() {
        return (String)readProperty(STATE_PROPERTY);
    }

    public void setWork(String work) {
        writeProperty(WORK_PROPERTY, work);
    }
    public String getWork() {
        return (String)readProperty(WORK_PROPERTY);
    }

    public void setEmployee(Employee employee) {
        setToOneTarget(EMPLOYEE_PROPERTY, employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty(EMPLOYEE_PROPERTY);
    }


}
