package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Area;

/**
 * Class _NCPerson was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCPerson extends CayenneDataObject {

    public static final String CUSTOMER_CD_PROPERTY = "customerCd";
    public static final String CUSTOMER_CD_ED_PROPERTY = "customerCdEd";
    public static final String DIVISION_CD_PROPERTY = "divisionCd";
    public static final String DIVISION_CD_ED_PROPERTY = "divisionCdEd";
    public static final String EMAIL1_PROPERTY = "email1";
    public static final String EMAIL2_PROPERTY = "email2";
    public static final String EMPNO_PROPERTY = "empno";
    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String OSM_YMD_PROPERTY = "osmYmd";
    public static final String OSM_YMD_SEQ_PROPERTY = "osmYmdSeq";
    public static final String TEL_NO1_PROPERTY = "telNo1";
    public static final String TEL_NO2_PROPERTY = "telNo2";
    public static final String AREA_PROPERTY = "area";

    public static final String CUSTOMERCD_PK_COLUMN = "CUSTOMERCD";
    public static final String CUSTOMERCD_ED_PK_COLUMN = "CUSTOMERCD_ED";
    public static final String DIVISIONCD_PK_COLUMN = "DIVISIONCD";
    public static final String DIVISIONCD_ED_PK_COLUMN = "DIVISIONCD_ED";
    public static final String OSMYMD_PK_COLUMN = "OSMYMD";
    public static final String OSMYMD_SEQ_PK_COLUMN = "OSMYMD_SEQ";

    public void setCustomerCd(int customerCd) {
        writeProperty(CUSTOMER_CD_PROPERTY, customerCd);
    }
    public int getCustomerCd() {
        Object value = readProperty(CUSTOMER_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setCustomerCdEd(int customerCdEd) {
        writeProperty(CUSTOMER_CD_ED_PROPERTY, customerCdEd);
    }
    public int getCustomerCdEd() {
        Object value = readProperty(CUSTOMER_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setDivisionCd(int divisionCd) {
        writeProperty(DIVISION_CD_PROPERTY, divisionCd);
    }
    public int getDivisionCd() {
        Object value = readProperty(DIVISION_CD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setDivisionCdEd(int divisionCdEd) {
        writeProperty(DIVISION_CD_ED_PROPERTY, divisionCdEd);
    }
    public int getDivisionCdEd() {
        Object value = readProperty(DIVISION_CD_ED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmail1(String email1) {
        writeProperty(EMAIL1_PROPERTY, email1);
    }
    public String getEmail1() {
        return (String)readProperty(EMAIL1_PROPERTY);
    }

    public void setEmail2(String email2) {
        writeProperty(EMAIL2_PROPERTY, email2);
    }
    public String getEmail2() {
        return (String)readProperty(EMAIL2_PROPERTY);
    }

    public void setEmpno(Integer empno) {
        writeProperty(EMPNO_PROPERTY, empno);
    }
    public Integer getEmpno() {
        return (Integer)readProperty(EMPNO_PROPERTY);
    }

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setOsmYmd(int osmYmd) {
        writeProperty(OSM_YMD_PROPERTY, osmYmd);
    }
    public int getOsmYmd() {
        Object value = readProperty(OSM_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOsmYmdSeq(int osmYmdSeq) {
        writeProperty(OSM_YMD_SEQ_PROPERTY, osmYmdSeq);
    }
    public int getOsmYmdSeq() {
        Object value = readProperty(OSM_YMD_SEQ_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTelNo1(int telNo1) {
        writeProperty(TEL_NO1_PROPERTY, telNo1);
    }
    public int getTelNo1() {
        Object value = readProperty(TEL_NO1_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTelNo2(int telNo2) {
        writeProperty(TEL_NO2_PROPERTY, telNo2);
    }
    public int getTelNo2() {
        Object value = readProperty(TEL_NO2_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setArea(Area area) {
        setToOneTarget(AREA_PROPERTY, area, true);
    }

    public Area getArea() {
        return (Area)readProperty(AREA_PROPERTY);
    }


}
