package jp.co.nexus.crm.db.auto;

import org.apache.cayenne.CayenneDataObject;

import jp.co.nexus.crm.db.Employee;

/**
 * Class _NCStandard was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NCStandard extends CayenneDataObject {

    public static final String LIMIT_YMD_PROPERTY = "limitYmd";
    public static final String LOST_YMD_PROPERTY = "lostYmd";
    public static final String LOWER_PROPERTY = "lower";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NAME_PROPERTY = "name";
    public static final String SHORT_NAME_PROPERTY = "shortName";
    public static final String STAND_KBN_PROPERTY = "standKbn";
    public static final String TOKKIC1_PROPERTY = "tokkic1";
    public static final String TOKKIC2_PROPERTY = "tokkic2";
    public static final String TOKKIC3_PROPERTY = "tokkic3";
    public static final String TOKKIC4_PROPERTY = "tokkic4";
    public static final String TOKKIC5_PROPERTY = "tokkic5";
    public static final String TOKKIN1_PROPERTY = "tokkin1";
    public static final String TOKKIN2_PROPERTY = "tokkin2";
    public static final String TOKKIN3_PROPERTY = "tokkin3";
    public static final String TOKKIN4_PROPERTY = "tokkin4";
    public static final String TOKKIN5_PROPERTY = "tokkin5";
    public static final String UPPER_PROPERTY = "upper";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String STANDCD_PK_COLUMN = "STANDCD";

    public void setLimitYmd(int limitYmd) {
        writeProperty(LIMIT_YMD_PROPERTY, limitYmd);
    }
    public int getLimitYmd() {
        Object value = readProperty(LIMIT_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLostYmd(int lostYmd) {
        writeProperty(LOST_YMD_PROPERTY, lostYmd);
    }
    public int getLostYmd() {
        Object value = readProperty(LOST_YMD_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setLower(int lower) {
        writeProperty(LOWER_PROPERTY, lower);
    }
    public int getLower() {
        Object value = readProperty(LOWER_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setModified(int modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public int getModified() {
        Object value = readProperty(MODIFIED_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setShortName(String shortName) {
        writeProperty(SHORT_NAME_PROPERTY, shortName);
    }
    public String getShortName() {
        return (String)readProperty(SHORT_NAME_PROPERTY);
    }

    public void setStandKbn(int standKbn) {
        writeProperty(STAND_KBN_PROPERTY, standKbn);
    }
    public int getStandKbn() {
        Object value = readProperty(STAND_KBN_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkic1(String tokkic1) {
        writeProperty(TOKKIC1_PROPERTY, tokkic1);
    }
    public String getTokkic1() {
        return (String)readProperty(TOKKIC1_PROPERTY);
    }

    public void setTokkic2(String tokkic2) {
        writeProperty(TOKKIC2_PROPERTY, tokkic2);
    }
    public String getTokkic2() {
        return (String)readProperty(TOKKIC2_PROPERTY);
    }

    public void setTokkic3(String tokkic3) {
        writeProperty(TOKKIC3_PROPERTY, tokkic3);
    }
    public String getTokkic3() {
        return (String)readProperty(TOKKIC3_PROPERTY);
    }

    public void setTokkic4(String tokkic4) {
        writeProperty(TOKKIC4_PROPERTY, tokkic4);
    }
    public String getTokkic4() {
        return (String)readProperty(TOKKIC4_PROPERTY);
    }

    public void setTokkic5(String tokkic5) {
        writeProperty(TOKKIC5_PROPERTY, tokkic5);
    }
    public String getTokkic5() {
        return (String)readProperty(TOKKIC5_PROPERTY);
    }

    public void setTokkin1(int tokkin1) {
        writeProperty(TOKKIN1_PROPERTY, tokkin1);
    }
    public int getTokkin1() {
        Object value = readProperty(TOKKIN1_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkin2(int tokkin2) {
        writeProperty(TOKKIN2_PROPERTY, tokkin2);
    }
    public int getTokkin2() {
        Object value = readProperty(TOKKIN2_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkin3(int tokkin3) {
        writeProperty(TOKKIN3_PROPERTY, tokkin3);
    }
    public int getTokkin3() {
        Object value = readProperty(TOKKIN3_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkin4(int tokkin4) {
        writeProperty(TOKKIN4_PROPERTY, tokkin4);
    }
    public int getTokkin4() {
        Object value = readProperty(TOKKIN4_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setTokkin5(int tokkin5) {
        writeProperty(TOKKIN5_PROPERTY, tokkin5);
    }
    public int getTokkin5() {
        Object value = readProperty(TOKKIN5_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setUpper(int upper) {
        writeProperty(UPPER_PROPERTY, upper);
    }
    public int getUpper() {
        Object value = readProperty(UPPER_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setEmployee(Employee employee) {
        setToOneTarget(EMPLOYEE_PROPERTY, employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty(EMPLOYEE_PROPERTY);
    }


}
