CREATE TABLE AREA (AREACD INTEGER NOT NULL, LAST_MODIFIED INTEGER NULL, LIMITYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, PRIMARY KEY (AREACD))
;

CREATE TABLE EMPLOYEE (AREACD INTEGER NOT NULL, EMAIL VARCHAR(40) NOT NULL, EMPNO INTEGER NOT NULL, EMPNO_ED INTEGER NOT NULL, ENTRYMD INTEGER NOT NULL, LAST_MODIFIED INTEGER NULL, LIMITYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, PASSWORD VARCHAR(20) NOT NULL, RETRYMD INTEGER NOT NULL, PRIMARY KEY (EMPNO))
;

CREATE TABLE NC_CALLDOC (AREACD INTEGER NOT NULL, CALLDOC VARCHAR(1000) NOT NULL, CALLTIME INTEGER NOT NULL, CALLYMD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, PERSONNO INTEGER NOT NULL, VISIT_RECORD_NO INTEGER NOT NULL, PRIMARY KEY (VISIT_RECORD_NO))
;

CREATE TABLE NC_PERSON (AREACD INTEGER NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(100) NOT NULL, PERSONAL_NO INTEGER NOT NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, PRIMARY KEY (PERSONAL_NO))
;

CREATE TABLE NC_CUSTOMER (ADDRESS VARCHAR(200) NULL, AREACD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, CUST_RANK_KBN01 INTEGER NOT NULL, CUST_RANK_KBN02 INTEGER NOT NULL, CUST_RANK_KBN03 INTEGER NOT NULL, CUST_RANK_KBN04 INTEGER NOT NULL, CUST_RANK_KBN05 INTEGER NOT NULL, CUST_RANK_KBN06 INTEGER NOT NULL, CUST_RANK_KBN07 INTEGER NOT NULL, CUST_RANK_KBN08 INTEGER NOT NULL, CUST_RANK_KBN09 INTEGER NOT NULL, CUST_RANK_KBN10 INTEGER NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INTEGER NULL, ITEM_RANK_KBN01 INTEGER NOT NULL, ITEM_RANK_KBN02 INTEGER NOT NULL, ITEM_RANK_KBN03 INTEGER NOT NULL, ITEM_RANK_KBN04 INTEGER NOT NULL, ITEM_RANK_KBN05 INTEGER NOT NULL, ITEM_RANK_KBN06 INTEGER NOT NULL, ITEM_RANK_KBN07 INTEGER NOT NULL, ITEM_RANK_KBN08 INTEGER NOT NULL, ITEM_RANK_KBN09 INTEGER NOT NULL, ITEM_RANK_KBN10 INTEGER NOT NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(60) NOT NULL, OUTSIDE_MAKE_KBN VARCHAR(10) NULL, OUTSIDE_MAKE_TOK VARCHAR(400) NULL, POSTNO VARCHAR(8) NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, PRIMARY KEY (CUSTOMERCD))
;

CREATE TABLE NC_DIVISION (AREACD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, TOKKI VARCHAR(100) NULL, PRIMARY KEY (DIVISIONCD))
;

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CALLDOC ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CALLDOC ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_PERSON ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_PERSON ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_CUSTOMER ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CUSTOMER ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_DIVISION ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_DIVISION ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('AREA', 'EMPLOYEE', 'NC_CALLDOC', 'NC_CUSTOMER', 'NC_DIVISION', 'NC_PERSON')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('AREA', 1)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('EMPLOYEE', 1)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CALLDOC', 1)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CUSTOMER', 1)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_DIVISION', 1)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_PERSON', 1)
;

