DROP TABLE NC_CUSTOMER
;

DROP TABLE NC_DIVISION
;

DROP TABLE NC_CALLDOC
;

DROP TABLE NC_PERSON
;

DROP TABLE NC_OUTSIDE_MAKE
;

DROP TABLE AREA
;

DROP TABLE NC_STANDARD
;

DROP TABLE EMPLOYEE
;

CREATE TABLE EMPLOYEE (EMAIL VARCHAR(40) NOT NULL, EMPNO INTEGER NOT NULL, EMPNO_ED INTEGER NOT NULL, ENTRYMD INTEGER NOT NULL, LAST_MODIFIED INTEGER NULL, LIMITYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, PASSWORD VARCHAR(20) NOT NULL, RETRYMD INTEGER NOT NULL, PRIMARY KEY (EMPNO))
;

CREATE TABLE NC_STANDARD (EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, LOWER INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, STANDCD INTEGER NOT NULL, STANDKBN INTEGER NOT NULL, TOKKIC1 VARCHAR(400) NULL, TOKKIC2 VARCHAR(400) NULL, TOKKIC3 VARCHAR(400) NULL, TOKKIC4 VARCHAR(400) NULL, TOKKIC5 VARCHAR(400) NULL, TOKKIN1 INTEGER NOT NULL, TOKKIN2 INTEGER NULL, TOKKIN3 INTEGER NULL, TOKKIN4 INTEGER NULL, TOKKIN5 INTEGER NULL, UPPER INTEGER NOT NULL, PRIMARY KEY (STANDCD))
;

CREATE TABLE AREA (AREACD INTEGER NOT NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMITYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, PRIMARY KEY (AREACD))
;

CREATE TABLE NC_OUTSIDE_MAKE (AREACD INTEGER NOT NULL, COMPETE VARCHAR(10) NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMPNO INTEGER NULL, INTARVIEW INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, MARKET_PRICE VARCHAR(10) NULL, NEED_SKILL VARCHAR(400) NULL, NUMPEPOLE INTEGER NULL, OSMYMD INTEGER NOT NULL, OSMYMD_SEQ INTEGER NOT NULL, OUTSIDE_MAKE_DTL VARCHAR(400) NULL, OUTSIDE_MAKE_KBN VARCHAR(10) NULL, PERIOD VARCHAR(20) NULL, PERSONNO INTEGER NOT NULL, PERSONNO_ED INTEGER NOT NULL, PLACE VARCHAR(100) NULL, SALES_CHANNEL VARCHAR(100) NULL, STATE VARCHAR(100) NULL, WORK VARCHAR(10) NULL, PRIMARY KEY (CUSTOMERCD))
;

CREATE TABLE NC_PERSON (AREACD INTEGER NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(100) NOT NULL, OSMYMD INTEGER NOT NULL, OSMYMD_SEQ INTEGER NOT NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, PRIMARY KEY (CUSTOMERCD))
;

CREATE TABLE NC_CALLDOC (AREACD INTEGER NOT NULL, CALLDOC VARCHAR(1000) NOT NULL, CALLTIME INTEGER NOT NULL, CALLYMD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, PERSONNO INTEGER NOT NULL, SALES_EMPNO INTEGER NOT NULL, SALES_EMPNO_ED INTEGER NOT NULL, PRIMARY KEY (SALES_EMPNO))
;

CREATE TABLE NC_DIVISION (AREACD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, DIVISIONCD INTEGER NOT NULL, DIVISIONCD_ED INTEGER NOT NULL, EMPNO INTEGER NULL, LAST_MODIFIED INTEGER NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, TOKKI VARCHAR(100) NULL, PRIMARY KEY (DIVISIONCD))
;

CREATE TABLE NC_CUSTOMER (ADDRESS VARCHAR(200) NULL, AREACD INTEGER NOT NULL, CUSTOMERCD INTEGER NOT NULL, CUSTOMERCD_ED INTEGER NOT NULL, CUST_RANK_KBN01 INTEGER NOT NULL, CUST_RANK_KBN02 INTEGER NOT NULL, CUST_RANK_KBN03 INTEGER NOT NULL, CUST_RANK_KBN04 INTEGER NOT NULL, CUST_RANK_KBN05 INTEGER NOT NULL, CUST_RANK_KBN06 INTEGER NOT NULL, CUST_RANK_KBN07 INTEGER NOT NULL, CUST_RANK_KBN08 INTEGER NOT NULL, CUST_RANK_KBN09 INTEGER NOT NULL, CUST_RANK_KBN10 INTEGER NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INTEGER NULL, ITEM_RANK_KBN01 INTEGER NOT NULL, ITEM_RANK_KBN02 INTEGER NOT NULL, ITEM_RANK_KBN03 INTEGER NOT NULL, ITEM_RANK_KBN04 INTEGER NOT NULL, ITEM_RANK_KBN05 INTEGER NOT NULL, ITEM_RANK_KBN06 INTEGER NOT NULL, ITEM_RANK_KBN07 INTEGER NOT NULL, ITEM_RANK_KBN08 INTEGER NOT NULL, ITEM_RANK_KBN09 INTEGER NOT NULL, ITEM_RANK_KBN10 INTEGER NOT NULL, LAST_MODIFIED INTEGER NULL, LIMTYMD INTEGER NOT NULL, LOSTYMD INTEGER NOT NULL, NAME VARCHAR(60) NOT NULL, OUTSIDE_MAKE_KBN VARCHAR(10) NULL, OUTSIDE_MAKE_TOK VARCHAR(400) NULL, POSTNO VARCHAR(8) NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, PRIMARY KEY (CUSTOMERCD))
;

ALTER TABLE NC_STANDARD ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE AREA ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_OUTSIDE_MAKE ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_PERSON ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CALLDOC ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CALLDOC ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_DIVISION ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_DIVISION ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

ALTER TABLE NC_CUSTOMER ADD FOREIGN KEY (AREACD) REFERENCES AREA (AREACD)
;

ALTER TABLE NC_CUSTOMER ADD FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;

DROP TABLE AUTO_PK_SUPPORT
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('AREA', 'EMPLOYEE', 'NC_CALLDOC', 'NC_CUSTOMER', 'NC_DIVISION', 'NC_OUTSIDE_MAKE', 'NC_PERSON', 'NC_STANDARD')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('AREA', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('EMPLOYEE', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CALLDOC', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CUSTOMER', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_DIVISION', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_OUTSIDE_MAKE', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_PERSON', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_STANDARD', 200)
;

