CREATE TABLE NC_PERSON (AREACD INT NOT NULL, CUSTOMERCD INT NOT NULL, CUSTOMERCD_ED INT NOT NULL, DIVISIONCD INT NOT NULL, DIVISIONCD_ED INT NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INT NULL, LIMTYMD INT NOT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(100) NOT NULL, OSMYMD INT NOT NULL, OSMYMD_SEQ INT NOT NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, `UPDATE` INT NULL, PRIMARY KEY (AREACD, CUSTOMERCD, CUSTOMERCD_ED, DIVISIONCD, DIVISIONCD_ED, OSMYMD, OSMYMD_SEQ)) ENGINE=InnoDB
;

CREATE TABLE AREA (AREACD INT NOT NULL, EMPNO INT NULL, LIMITYMD INT NOT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, `UPDATE` INT NULL, PRIMARY KEY (AREACD)) ENGINE=InnoDB
;

CREATE TABLE EMPLOYEE (EMAIL VARCHAR(40) NOT NULL, EMPNO INT NOT NULL, EMPNO_ED INT NOT NULL, ENTRYMD INT NOT NULL, LIMITYMD INT NOT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(40) NOT NULL, PASSWORD VARCHAR(20) NOT NULL, RETRYMD INT NOT NULL, `UPDATE` INT NOT NULL, PRIMARY KEY (EMPNO, EMPNO_ED)) ENGINE=InnoDB
;

CREATE TABLE NC_OUTSIDE_MAKE (AREACD INT NOT NULL, COMPETE VARCHAR(10) NULL, CUSTOMERCD INT NOT NULL, CUSTOMERCD_ED INT NOT NULL, DIVISIONCD INT NOT NULL, DIVISIONCD_ED INT NOT NULL, EMPNO INT NULL, INTARVIEW INT NULL, LIMTYMD INT NOT NULL, LOSTYMD INT NOT NULL, MARKET_PRICE VARCHAR(10) NULL, NEED_SKILL VARCHAR(400) NULL, NUMPEPOLE INT NULL, OSMYMD INT NOT NULL, OSMYMD_SEQ INT NOT NULL, OUTSIDE_MAKE_DTL VARCHAR(400) NULL, OUTSIDE_MAKE_KBN VARCHAR(10) NULL, PERIOD VARCHAR(20) NULL, PERSONNO INT NOT NULL, PERSONNO_ED INT NOT NULL, PLACE VARCHAR(100) NULL, SALES_CHANNEL VARCHAR(100) NULL, STATE VARCHAR(100) NULL, `UPDATE` INT NULL, WORK VARCHAR(10) NULL, PRIMARY KEY (AREACD, CUSTOMERCD, CUSTOMERCD_ED, DIVISIONCD, DIVISIONCD_ED, OSMYMD, OSMYMD_SEQ)) ENGINE=InnoDB
;

CREATE TABLE NC_CALLDOC (AREACD INT NOT NULL, CALLDOC VARCHAR(1000) NOT NULL, CALLTIME INT NOT NULL, CALLYMD INT NOT NULL, CUSTOMERCD INT NOT NULL, CUSTOMERCD_ED INT NOT NULL, DIVISIONCD INT NOT NULL, DIVISIONCD_ED INT NOT NULL, EMPNO INT NULL, LIMTYMD INT NOT NULL, LOSTYMD INT NOT NULL, PERSONNO INT NOT NULL, SALES_EMPNO INT NOT NULL, SALES_EMPNO_ED INT NOT NULL, `UPDATE` INT NULL, PRIMARY KEY (AREACD, CALLTIME, CALLYMD, CUSTOMERCD, CUSTOMERCD_ED, DIVISIONCD, DIVISIONCD_ED, SALES_EMPNO, SALES_EMPNO_ED)) ENGINE=InnoDB
;

CREATE TABLE NC_STANDARD (EMPNO INT NULL, LIMTYMD INT NOT NULL, LOSTYMD INT NOT NULL, LOWER INT NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, STANDCD INT NOT NULL, STANDKBN INT NOT NULL, TOKKIC1 VARCHAR(400) NULL, TOKKIC2 VARCHAR(400) NULL, TOKKIC3 VARCHAR(400) NULL, TOKKIC4 VARCHAR(400) NULL, TOKKIC5 VARCHAR(400) NULL, TOKKIN1 INT NOT NULL, TOKKIN2 INT NULL, TOKKIN3 INT NULL, TOKKIN4 INT NULL, TOKKIN5 INT NULL, `UPDATE` INT NULL, UPPER INT NOT NULL, PRIMARY KEY (STANDCD, STANDKBN)) ENGINE=InnoDB
;

CREATE TABLE NC_COMMON_NM (COMMONCD INT NOT NULL, COMMONKBN INT NOT NULL, EMPNO INT NULL, LIMITYMD INT NOT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, TOKKIC1 VARCHAR(400) NULL, TOKKIC2 VARCHAR(400) NULL, TOKKIC3 VARCHAR(400) NULL, TOKKIC4 VARCHAR(400) NULL, TOKKIC5 VARCHAR(400) NULL, TOKKIN1 INT NOT NULL, TOKKIN2 INT NULL, TOKKIN3 INT NULL, TOKKIN4 INT NULL, TOKKIN5 INT NULL, `UPDATE` INT NULL, PRIMARY KEY (COMMONCD, COMMONKBN)) ENGINE=InnoDB
;

CREATE TABLE NC_CUSTOMER (ADDRESS VARCHAR(200) NULL, AREACD INT NOT NULL, CUSTOMERCD INT NOT NULL, CUSTOMERCD_ED INT NOT NULL, CUST_RANK_KBN01 INT NOT NULL, CUST_RANK_KBN02 INT NOT NULL, CUST_RANK_KBN03 INT NOT NULL, CUST_RANK_KBN04 INT NOT NULL, CUST_RANK_KBN05 INT NOT NULL, CUST_RANK_KBN06 INT NOT NULL, CUST_RANK_KBN07 INT NOT NULL, CUST_RANK_KBN08 INT NOT NULL, CUST_RANK_KBN09 INT NOT NULL, CUST_RANK_KBN10 INT NOT NULL, EMAIL1 VARCHAR(100) NULL, EMAIL2 VARCHAR(100) NULL, EMPNO INT NULL, ITEM_RANK_KBN01 INT NOT NULL, ITEM_RANK_KBN02 INT NOT NULL, ITEM_RANK_KBN03 INT NOT NULL, ITEM_RANK_KBN04 INT NOT NULL, ITEM_RANK_KBN05 INT NOT NULL, ITEM_RANK_KBN06 INT NOT NULL, ITEM_RANK_KBN07 INT NOT NULL, ITEM_RANK_KBN08 INT NOT NULL, ITEM_RANK_KBN09 INT NOT NULL, ITEM_RANK_KBN10 INT NOT NULL, LIMTYMD INT NOT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(60) NOT NULL, OUTSIDE_MAKE_KBN VARCHAR(10) NULL, OUTSIDE_MAKE_TOK VARCHAR(400) NULL, POSTNO VARCHAR(8) NULL, TELNO1 VARCHAR(15) NULL, TELNO2 VARCHAR(15) NULL, `UPDATE` INT NULL, PRIMARY KEY (CUSTOMERCD, CUSTOMERCD_ED)) ENGINE=InnoDB
;

CREATE TABLE NC_DIVISION (AREACD INT NOT NULL, CUSTOMERCD INT NOT NULL, CUSTOMERCD_ED INT NOT NULL, DIVISIONCD INT NOT NULL, DIVISIONCD_ED INT NOT NULL, EMPNO INT NULL, LOSTYMD INT NOT NULL, NAME VARCHAR(40) NOT NULL, SHORT_NAME VARCHAR(40) NOT NULL, TOKKI VARCHAR(100) NULL, `UPDATE` INT NULL, PRIMARY KEY (AREACD, CUSTOMERCD, CUSTOMERCD_ED, DIVISIONCD, DIVISIONCD_ED)) ENGINE=InnoDB
;

CREATE TABLE AUTO_PK_SUPPORT (  TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL, UNIQUE (TABLE_NAME))
;

DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('AREA', 'EMPLOYEE', 'NC_CALLDOC', 'NC_COMMON_NM', 'NC_CUSTOMER', 'NC_DIVISION', 'NC_OUTSIDE_MAKE', 'NC_PERSON', 'NC_STANDARD')
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('AREA', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('EMPLOYEE', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CALLDOC', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_COMMON_NM', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_CUSTOMER', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_DIVISION', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_OUTSIDE_MAKE', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_PERSON', 200)
;

INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('NC_STANDARD', 200)
;

